version: '3.6'

services:
  alpine-apache2-http-and-https-hl:
    build: .
    image: hackinglab/alpine-apache2-http-and-https-hl:3.2
    environment:
      - "HL_USER_USERNAME=hacker"
      - "HL_USER_PASSWORD=compass"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/opt/www
